#include <cstdlib>
#include <exception>

int main()
{
    std::exit(1);
}
