#include <exception>

int main()
{
    std::terminate();
}
